apiVersion: v1
kind: Template
metadata:
  name: s2i-chained-build-template
  annotations:
    iconClass: icon-java
    openshift.io/display-name: S2I Chained Build
    openshift.io/provider-display-name: ubi-mvn-builder
    template.openshift.io/long-description: S2I build of Java application (<app-name>-build-artifacts image) followed by a build to create a lightweight application image (<app-name> image). <app-name> image 
    description: S2I build of Java application (<app-name>-build-artifacts image) followed by a build to create a lightweight application image (<app-name> image). <app-name> image 
  message: Builds created.
labels:
  template: s2i-chained-build-template
parameters:
- name: APPLICATION_NAME
  description: The application name. Name is assigned to all of the application objects defined in this template.
  displayName: Image Name
  required: true
  value: cats
- name: GIT_REPO
  description: The application git repository
  displayName: git repository
  required: true
  value: https://github.com/petbattle/pet-battle-api.git
- name: GIT_CONTEXT_DIR
  description: The application git repository sub directory
  displayName: git repository sub directory
  required: false
  value:
- name: GIT_BRANCH
  description: The application git branch
  displayName: git branch
  required: false
  value: master
- name: IMAGE_STREAM_NAMESPACE
  description: Namespace in which the ImageStreams are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
  displayName: ImageStreams Namespace
  required: true
  value: openshift
- name: MAVEN_BUILD_OPTS
  description: Maven Build Options (default if not set -Pnative)
  displayName: maven build Options (default if not set -Pnative)
  required: false
  value: "-Dquarkus.package.type=fast-jar -DskipTests"
- name: MAVEN_CLEAR_REPO
  description: Clean Maven .m2 repo after build (default false)
  displayName: Clean Maven .m2 repo after build (default false)
  required: false
  value: "true"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ubi-mvn-builder
    labels:
      app: ${APPLICATION_NAME}-build-artifacts
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: quay.io/eformat/ubi-mvn-builder:latest
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}-build-artifacts
    name: ${APPLICATION_NAME}-build-artifacts
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}-build-artifacts
    name: ${APPLICATION_NAME}-build-artifacts
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}-build-artifacts:latest
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_BRANCH}
        uri: ${GIT_REPO}
      contextDir: ${GIT_CONTEXT_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ubi-mvn-builder
          namespace: ${IMAGE_STREAM_NAMESPACE}
        env:
          - name: "MAVEN_BUILD_OPTS"
            value: ${MAVEN_BUILD_OPTS}
          - name: "MAVEN_CLEAR_REPO"
            value: ${MAVEN_CLEAR_REPO}
      type: Source
    triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      dockerfile: |-
        FROM wildfly-runtime-centos7:latest
        COPY /server $JBOSS_HOME
        USER root
        RUN chown -R jboss:root $JBOSS_HOME && chmod -R ug+rwX $JBOSS_HOME
        RUN ln -s $JBOSS_HOME /wildfly 
        USER jboss
        CMD $JBOSS_HOME/bin/openshift-launch.sh
      images:
        - from: 
            kind: ImageStreamTag
            name: ${APPLICATION_NAME}-build-artifacts:latest
          paths: 
          - sourcePath: /s2i-output/server/
            destinationDir: "."
    strategy:
      dockerStrategy:
        imageOptimizationPolicy: SkipLayers
        from:
          kind: ImageStreamTag
          name: wildfly-runtime:latest
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Docker
    triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}-build-artifacts:latest
    - type: ConfigChange
    