name: Build containers

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * 0'

env:
  REGISTRY: quay.io
  BASE_IMAGE_NAME: eformat/ubi-mvn-builder
  JVM_IMAGE_NAME: eformat/ubi-mvn-runtime-jvm
  NATIVE_IMAGE_NAME: eformat/ubi-mvn-runtime-native
  TAGS: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Build base image
      - name: Buildah Base Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.BASE_IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          context: builder
          containerfiles: |
            ./builder/Dockerfile

      # Build JVM image
      - name: Buildah JVM Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.JVM_IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          context: runtime
          containerfiles: |
            ./runtime/Dockerfile.jvm

      # Build Native image
      - name: Buildah Native Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NATIVE_IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          context: runtime
          containerfiles: |
            ./runtime/Dockerfile.native

      # Login to Registry
      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USER }}      # ${{ github.actor }} - for ghcr.io
          password: ${{ secrets.QUAY_TOKEN }}     # quay.io
      #   password: ${{ secrets.GITHUB_TOKEN }}   # ghcr.io

      - name: Push Base to Container Repository
        id: push-to-registry-base
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.BASE_IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          registry: ${{ env.REGISTRY }}

      - name: Push JVM to Container Repository
        id: push-to-registry-jvm
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.JVM_IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          registry: ${{ env.REGISTRY }}

      - name: Push Native to Container Repository
        id: push-to-registry-native
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.NATIVE_IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          registry: ${{ env.REGISTRY }}

      # Provenance signing image
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.1.1'

      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.SIGNING_SECRET }}" > cosign.key

      - name: Sign container Base image
        run: |
          cosign sign --key cosign.key \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            -y \
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:${{ env.TAGS }}
        env:
          COSIGN_PASSWORD: ""

      - name: Sign container JVM image
        run: |
          cosign sign --key cosign.key \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            -y \
            ${{ env.REGISTRY }}/${{ env.JVM_IMAGE_NAME }}:${{ env.TAGS }}
        env:
          COSIGN_PASSWORD: ""

      - name: Sign container Native image
        run: |
          cosign sign --key cosign.key \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            -y \
            ${{ env.REGISTRY }}/${{ env.NATIVE_IMAGE_NAME }}:${{ env.TAGS }}
        env:
          COSIGN_PASSWORD: ""